# Generated by Django 4.2.6 on 2023-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.TextField(default='No Certificate', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.TextField(default='No Hobby', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
